FROM mcr.microsoft.com/devcontainers/universal:2
RUN apt-get update \
    && apt-get install -y lilypond \
    && apt-get install -y texlive-latex-base \
    && apt-get install -y latex-cjk-all \
    && apt-get install -y texlive-xetex